import { colorTokens, typography } from '@/theme';

export const Colors = {
  light: {
    text: colorTokens.light.text,
    background: colorTokens.light.background,
    tint: colorTokens.light.primary,
    icon: colorTokens.light.muted,
    tabIconDefault: colorTokens.light.muted,
    tabIconSelected: colorTokens.light.primary,
    surface: colorTokens.light.surface,
    surfaceLow: colorTokens.light.surfaceLow,
    surfaceLowest: colorTokens.light.surfaceLowest,
    surfaceHigh: colorTokens.light.surfaceHigh,
    primaryStrong: colorTokens.light.primaryStrong,
    primaryOn: colorTokens.light.primaryOn,
    ctaGradientStart: colorTokens.light.ctaGradientStart,
    ctaGradientEnd: colorTokens.light.ctaGradientEnd,
    mutedSoft: colorTokens.light.mutedSoft,
    separator: colorTokens.light.separator,
    tabBarBackground: colorTokens.light.tabBarBackground,
    tabActive: colorTokens.light.tabActive,
    tabInactive: colorTokens.light.tabInactive,
    info: colorTokens.light.info,
    success: colorTokens.light.success,
    error: colorTokens.light.error,
  },
  dark: {
    text: colorTokens.dark.text,
    background: colorTokens.dark.background,
    tint: colorTokens.dark.primary,
    icon: colorTokens.dark.muted,
    tabIconDefault: colorTokens.dark.muted,
    tabIconSelected: colorTokens.dark.primary,
    surface: colorTokens.dark.surface,
    surfaceLow: colorTokens.dark.surfaceLow,
    surfaceLowest: colorTokens.dark.surfaceLowest,
    surfaceHigh: colorTokens.dark.surfaceHigh,
    primaryStrong: colorTokens.dark.primaryStrong,
    primaryOn: colorTokens.dark.primaryOn,
    ctaGradientStart: colorTokens.dark.ctaGradientStart,
    ctaGradientEnd: colorTokens.dark.ctaGradientEnd,
    mutedSoft: colorTokens.dark.mutedSoft,
    separator: colorTokens.dark.separator,
    tabBarBackground: colorTokens.dark.tabBarBackground,
    tabActive: colorTokens.dark.tabActive,
    tabInactive: colorTokens.dark.tabInactive,
    info: colorTokens.dark.info,
    success: colorTokens.dark.success,
    error: colorTokens.dark.error,
  },
};

export const Fonts = typography.families;
